// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

/**
 * Protobuf type {@code AlterarFaltasResponse}
 */
public final class AlterarFaltasResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AlterarFaltasResponse)
    AlterarFaltasResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AlterarFaltasResponse.newBuilder() to construct.
  private AlterarFaltasResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AlterarFaltasResponse() {
    codigoDisciplina_ = "";
    mensagem_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AlterarFaltasResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_AlterarFaltasResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_AlterarFaltasResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AlterarFaltasResponse.class, AlterarFaltasResponse.Builder.class);
  }

  public static final int RA_FIELD_NUMBER = 1;
  private int ra_;
  /**
   * <code>int32 ra = 1;</code>
   * @return The ra.
   */
  @java.lang.Override
  public int getRa() {
    return ra_;
  }

  public static final int CODIGODISCIPLINA_FIELD_NUMBER = 2;
  private volatile java.lang.Object codigoDisciplina_;
  /**
   * <code>string codigoDisciplina = 2;</code>
   * @return The codigoDisciplina.
   */
  @java.lang.Override
  public java.lang.String getCodigoDisciplina() {
    java.lang.Object ref = codigoDisciplina_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codigoDisciplina_ = s;
      return s;
    }
  }
  /**
   * <code>string codigoDisciplina = 2;</code>
   * @return The bytes for codigoDisciplina.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodigoDisciplinaBytes() {
    java.lang.Object ref = codigoDisciplina_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codigoDisciplina_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANO_FIELD_NUMBER = 3;
  private int ano_;
  /**
   * <code>int32 ano = 3;</code>
   * @return The ano.
   */
  @java.lang.Override
  public int getAno() {
    return ano_;
  }

  public static final int SEMESTRE_FIELD_NUMBER = 4;
  private int semestre_;
  /**
   * <code>int32 semestre = 4;</code>
   * @return The semestre.
   */
  @java.lang.Override
  public int getSemestre() {
    return semestre_;
  }

  public static final int FALTAS_FIELD_NUMBER = 5;
  private int faltas_;
  /**
   * <code>int32 faltas = 5;</code>
   * @return The faltas.
   */
  @java.lang.Override
  public int getFaltas() {
    return faltas_;
  }

  public static final int MENSAGEM_FIELD_NUMBER = 6;
  private volatile java.lang.Object mensagem_;
  /**
   * <code>string mensagem = 6;</code>
   * @return The mensagem.
   */
  @java.lang.Override
  public java.lang.String getMensagem() {
    java.lang.Object ref = mensagem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mensagem_ = s;
      return s;
    }
  }
  /**
   * <code>string mensagem = 6;</code>
   * @return The bytes for mensagem.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMensagemBytes() {
    java.lang.Object ref = mensagem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mensagem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ra_ != 0) {
      output.writeInt32(1, ra_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigoDisciplina_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, codigoDisciplina_);
    }
    if (ano_ != 0) {
      output.writeInt32(3, ano_);
    }
    if (semestre_ != 0) {
      output.writeInt32(4, semestre_);
    }
    if (faltas_ != 0) {
      output.writeInt32(5, faltas_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mensagem_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ra_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ra_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigoDisciplina_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, codigoDisciplina_);
    }
    if (ano_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, ano_);
    }
    if (semestre_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, semestre_);
    }
    if (faltas_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, faltas_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mensagem_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AlterarFaltasResponse)) {
      return super.equals(obj);
    }
    AlterarFaltasResponse other = (AlterarFaltasResponse) obj;

    if (getRa()
        != other.getRa()) return false;
    if (!getCodigoDisciplina()
        .equals(other.getCodigoDisciplina())) return false;
    if (getAno()
        != other.getAno()) return false;
    if (getSemestre()
        != other.getSemestre()) return false;
    if (getFaltas()
        != other.getFaltas()) return false;
    if (!getMensagem()
        .equals(other.getMensagem())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RA_FIELD_NUMBER;
    hash = (53 * hash) + getRa();
    hash = (37 * hash) + CODIGODISCIPLINA_FIELD_NUMBER;
    hash = (53 * hash) + getCodigoDisciplina().hashCode();
    hash = (37 * hash) + ANO_FIELD_NUMBER;
    hash = (53 * hash) + getAno();
    hash = (37 * hash) + SEMESTRE_FIELD_NUMBER;
    hash = (53 * hash) + getSemestre();
    hash = (37 * hash) + FALTAS_FIELD_NUMBER;
    hash = (53 * hash) + getFaltas();
    hash = (37 * hash) + MENSAGEM_FIELD_NUMBER;
    hash = (53 * hash) + getMensagem().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AlterarFaltasResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AlterarFaltasResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AlterarFaltasResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AlterarFaltasResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AlterarFaltasResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AlterarFaltasResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AlterarFaltasResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AlterarFaltasResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AlterarFaltasResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AlterarFaltasResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AlterarFaltasResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AlterarFaltasResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AlterarFaltasResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AlterarFaltasResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AlterarFaltasResponse)
      AlterarFaltasResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_AlterarFaltasResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_AlterarFaltasResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AlterarFaltasResponse.class, AlterarFaltasResponse.Builder.class);
    }

    // Construct using AlterarFaltasResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ra_ = 0;

      codigoDisciplina_ = "";

      ano_ = 0;

      semestre_ = 0;

      faltas_ = 0;

      mensagem_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_AlterarFaltasResponse_descriptor;
    }

    @java.lang.Override
    public AlterarFaltasResponse getDefaultInstanceForType() {
      return AlterarFaltasResponse.getDefaultInstance();
    }

    @java.lang.Override
    public AlterarFaltasResponse build() {
      AlterarFaltasResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public AlterarFaltasResponse buildPartial() {
      AlterarFaltasResponse result = new AlterarFaltasResponse(this);
      result.ra_ = ra_;
      result.codigoDisciplina_ = codigoDisciplina_;
      result.ano_ = ano_;
      result.semestre_ = semestre_;
      result.faltas_ = faltas_;
      result.mensagem_ = mensagem_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AlterarFaltasResponse) {
        return mergeFrom((AlterarFaltasResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AlterarFaltasResponse other) {
      if (other == AlterarFaltasResponse.getDefaultInstance()) return this;
      if (other.getRa() != 0) {
        setRa(other.getRa());
      }
      if (!other.getCodigoDisciplina().isEmpty()) {
        codigoDisciplina_ = other.codigoDisciplina_;
        onChanged();
      }
      if (other.getAno() != 0) {
        setAno(other.getAno());
      }
      if (other.getSemestre() != 0) {
        setSemestre(other.getSemestre());
      }
      if (other.getFaltas() != 0) {
        setFaltas(other.getFaltas());
      }
      if (!other.getMensagem().isEmpty()) {
        mensagem_ = other.mensagem_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ra_ = input.readInt32();

              break;
            } // case 8
            case 18: {
              codigoDisciplina_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              ano_ = input.readInt32();

              break;
            } // case 24
            case 32: {
              semestre_ = input.readInt32();

              break;
            } // case 32
            case 40: {
              faltas_ = input.readInt32();

              break;
            } // case 40
            case 50: {
              mensagem_ = input.readStringRequireUtf8();

              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int ra_ ;
    /**
     * <code>int32 ra = 1;</code>
     * @return The ra.
     */
    @java.lang.Override
    public int getRa() {
      return ra_;
    }
    /**
     * <code>int32 ra = 1;</code>
     * @param value The ra to set.
     * @return This builder for chaining.
     */
    public Builder setRa(int value) {
      
      ra_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ra = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRa() {
      
      ra_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object codigoDisciplina_ = "";
    /**
     * <code>string codigoDisciplina = 2;</code>
     * @return The codigoDisciplina.
     */
    public java.lang.String getCodigoDisciplina() {
      java.lang.Object ref = codigoDisciplina_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codigoDisciplina_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string codigoDisciplina = 2;</code>
     * @return The bytes for codigoDisciplina.
     */
    public com.google.protobuf.ByteString
        getCodigoDisciplinaBytes() {
      java.lang.Object ref = codigoDisciplina_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codigoDisciplina_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string codigoDisciplina = 2;</code>
     * @param value The codigoDisciplina to set.
     * @return This builder for chaining.
     */
    public Builder setCodigoDisciplina(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codigoDisciplina_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string codigoDisciplina = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCodigoDisciplina() {
      
      codigoDisciplina_ = getDefaultInstance().getCodigoDisciplina();
      onChanged();
      return this;
    }
    /**
     * <code>string codigoDisciplina = 2;</code>
     * @param value The bytes for codigoDisciplina to set.
     * @return This builder for chaining.
     */
    public Builder setCodigoDisciplinaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codigoDisciplina_ = value;
      onChanged();
      return this;
    }

    private int ano_ ;
    /**
     * <code>int32 ano = 3;</code>
     * @return The ano.
     */
    @java.lang.Override
    public int getAno() {
      return ano_;
    }
    /**
     * <code>int32 ano = 3;</code>
     * @param value The ano to set.
     * @return This builder for chaining.
     */
    public Builder setAno(int value) {
      
      ano_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ano = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAno() {
      
      ano_ = 0;
      onChanged();
      return this;
    }

    private int semestre_ ;
    /**
     * <code>int32 semestre = 4;</code>
     * @return The semestre.
     */
    @java.lang.Override
    public int getSemestre() {
      return semestre_;
    }
    /**
     * <code>int32 semestre = 4;</code>
     * @param value The semestre to set.
     * @return This builder for chaining.
     */
    public Builder setSemestre(int value) {
      
      semestre_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 semestre = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSemestre() {
      
      semestre_ = 0;
      onChanged();
      return this;
    }

    private int faltas_ ;
    /**
     * <code>int32 faltas = 5;</code>
     * @return The faltas.
     */
    @java.lang.Override
    public int getFaltas() {
      return faltas_;
    }
    /**
     * <code>int32 faltas = 5;</code>
     * @param value The faltas to set.
     * @return This builder for chaining.
     */
    public Builder setFaltas(int value) {
      
      faltas_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 faltas = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFaltas() {
      
      faltas_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object mensagem_ = "";
    /**
     * <code>string mensagem = 6;</code>
     * @return The mensagem.
     */
    public java.lang.String getMensagem() {
      java.lang.Object ref = mensagem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensagem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mensagem = 6;</code>
     * @return The bytes for mensagem.
     */
    public com.google.protobuf.ByteString
        getMensagemBytes() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensagem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mensagem = 6;</code>
     * @param value The mensagem to set.
     * @return This builder for chaining.
     */
    public Builder setMensagem(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mensagem_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mensagem = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMensagem() {
      
      mensagem_ = getDefaultInstance().getMensagem();
      onChanged();
      return this;
    }
    /**
     * <code>string mensagem = 6;</code>
     * @param value The bytes for mensagem to set.
     * @return This builder for chaining.
     */
    public Builder setMensagemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mensagem_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AlterarFaltasResponse)
  }

  // @@protoc_insertion_point(class_scope:AlterarFaltasResponse)
  private static final AlterarFaltasResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AlterarFaltasResponse();
  }

  public static AlterarFaltasResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlterarFaltasResponse>
      PARSER = new com.google.protobuf.AbstractParser<AlterarFaltasResponse>() {
    @java.lang.Override
    public AlterarFaltasResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AlterarFaltasResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlterarFaltasResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public AlterarFaltasResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

