// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface AlterarFaltasResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AlterarFaltasResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ra = 1;</code>
   * @return The ra.
   */
  int getRa();

  /**
   * <code>string codigoDisciplina = 2;</code>
   * @return The codigoDisciplina.
   */
  java.lang.String getCodigoDisciplina();
  /**
   * <code>string codigoDisciplina = 2;</code>
   * @return The bytes for codigoDisciplina.
   */
  com.google.protobuf.ByteString
      getCodigoDisciplinaBytes();

  /**
   * <code>int32 ano = 3;</code>
   * @return The ano.
   */
  int getAno();

  /**
   * <code>int32 semestre = 4;</code>
   * @return The semestre.
   */
  int getSemestre();

  /**
   * <code>int32 faltas = 5;</code>
   * @return The faltas.
   */
  int getFaltas();

  /**
   * <code>string mensagem = 6;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>string mensagem = 6;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();
}
