// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

/**
 * Protobuf type {@code InserirMatriculaResponse}
 */
public final class InserirMatriculaResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InserirMatriculaResponse)
    InserirMatriculaResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InserirMatriculaResponse.newBuilder() to construct.
  private InserirMatriculaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InserirMatriculaResponse() {
    mensagem_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InserirMatriculaResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_InserirMatriculaResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_InserirMatriculaResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            InserirMatriculaResponse.class, InserirMatriculaResponse.Builder.class);
  }

  public static final int MATRICULA_FIELD_NUMBER = 1;
  private Matricula matricula_;
  /**
   * <code>.Matricula matricula = 1;</code>
   * @return Whether the matricula field is set.
   */
  @java.lang.Override
  public boolean hasMatricula() {
    return matricula_ != null;
  }
  /**
   * <code>.Matricula matricula = 1;</code>
   * @return The matricula.
   */
  @java.lang.Override
  public Matricula getMatricula() {
    return matricula_ == null ? Matricula.getDefaultInstance() : matricula_;
  }
  /**
   * <code>.Matricula matricula = 1;</code>
   */
  @java.lang.Override
  public MatriculaOrBuilder getMatriculaOrBuilder() {
    return getMatricula();
  }

  public static final int MENSAGEM_FIELD_NUMBER = 2;
  private volatile java.lang.Object mensagem_;
  /**
   * <code>string mensagem = 2;</code>
   * @return The mensagem.
   */
  @java.lang.Override
  public java.lang.String getMensagem() {
    java.lang.Object ref = mensagem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mensagem_ = s;
      return s;
    }
  }
  /**
   * <code>string mensagem = 2;</code>
   * @return The bytes for mensagem.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMensagemBytes() {
    java.lang.Object ref = mensagem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mensagem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (matricula_ != null) {
      output.writeMessage(1, getMatricula());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mensagem_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (matricula_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMatricula());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mensagem_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof InserirMatriculaResponse)) {
      return super.equals(obj);
    }
    InserirMatriculaResponse other = (InserirMatriculaResponse) obj;

    if (hasMatricula() != other.hasMatricula()) return false;
    if (hasMatricula()) {
      if (!getMatricula()
          .equals(other.getMatricula())) return false;
    }
    if (!getMensagem()
        .equals(other.getMensagem())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMatricula()) {
      hash = (37 * hash) + MATRICULA_FIELD_NUMBER;
      hash = (53 * hash) + getMatricula().hashCode();
    }
    hash = (37 * hash) + MENSAGEM_FIELD_NUMBER;
    hash = (53 * hash) + getMensagem().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static InserirMatriculaResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InserirMatriculaResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InserirMatriculaResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InserirMatriculaResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InserirMatriculaResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InserirMatriculaResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InserirMatriculaResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InserirMatriculaResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static InserirMatriculaResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static InserirMatriculaResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static InserirMatriculaResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InserirMatriculaResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(InserirMatriculaResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InserirMatriculaResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InserirMatriculaResponse)
      InserirMatriculaResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_InserirMatriculaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_InserirMatriculaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InserirMatriculaResponse.class, InserirMatriculaResponse.Builder.class);
    }

    // Construct using InserirMatriculaResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (matriculaBuilder_ == null) {
        matricula_ = null;
      } else {
        matricula_ = null;
        matriculaBuilder_ = null;
      }
      mensagem_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_InserirMatriculaResponse_descriptor;
    }

    @java.lang.Override
    public InserirMatriculaResponse getDefaultInstanceForType() {
      return InserirMatriculaResponse.getDefaultInstance();
    }

    @java.lang.Override
    public InserirMatriculaResponse build() {
      InserirMatriculaResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public InserirMatriculaResponse buildPartial() {
      InserirMatriculaResponse result = new InserirMatriculaResponse(this);
      if (matriculaBuilder_ == null) {
        result.matricula_ = matricula_;
      } else {
        result.matricula_ = matriculaBuilder_.build();
      }
      result.mensagem_ = mensagem_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof InserirMatriculaResponse) {
        return mergeFrom((InserirMatriculaResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(InserirMatriculaResponse other) {
      if (other == InserirMatriculaResponse.getDefaultInstance()) return this;
      if (other.hasMatricula()) {
        mergeMatricula(other.getMatricula());
      }
      if (!other.getMensagem().isEmpty()) {
        mensagem_ = other.mensagem_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMatriculaFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              mensagem_ = input.readStringRequireUtf8();

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private Matricula matricula_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Matricula, Matricula.Builder, MatriculaOrBuilder> matriculaBuilder_;
    /**
     * <code>.Matricula matricula = 1;</code>
     * @return Whether the matricula field is set.
     */
    public boolean hasMatricula() {
      return matriculaBuilder_ != null || matricula_ != null;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     * @return The matricula.
     */
    public Matricula getMatricula() {
      if (matriculaBuilder_ == null) {
        return matricula_ == null ? Matricula.getDefaultInstance() : matricula_;
      } else {
        return matriculaBuilder_.getMessage();
      }
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Builder setMatricula(Matricula value) {
      if (matriculaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        matricula_ = value;
        onChanged();
      } else {
        matriculaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Builder setMatricula(
        Matricula.Builder builderForValue) {
      if (matriculaBuilder_ == null) {
        matricula_ = builderForValue.build();
        onChanged();
      } else {
        matriculaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Builder mergeMatricula(Matricula value) {
      if (matriculaBuilder_ == null) {
        if (matricula_ != null) {
          matricula_ =
            Matricula.newBuilder(matricula_).mergeFrom(value).buildPartial();
        } else {
          matricula_ = value;
        }
        onChanged();
      } else {
        matriculaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Builder clearMatricula() {
      if (matriculaBuilder_ == null) {
        matricula_ = null;
        onChanged();
      } else {
        matricula_ = null;
        matriculaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Matricula.Builder getMatriculaBuilder() {
      
      onChanged();
      return getMatriculaFieldBuilder().getBuilder();
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public MatriculaOrBuilder getMatriculaOrBuilder() {
      if (matriculaBuilder_ != null) {
        return matriculaBuilder_.getMessageOrBuilder();
      } else {
        return matricula_ == null ?
            Matricula.getDefaultInstance() : matricula_;
      }
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Matricula, Matricula.Builder, MatriculaOrBuilder> 
        getMatriculaFieldBuilder() {
      if (matriculaBuilder_ == null) {
        matriculaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Matricula, Matricula.Builder, MatriculaOrBuilder>(
                getMatricula(),
                getParentForChildren(),
                isClean());
        matricula_ = null;
      }
      return matriculaBuilder_;
    }

    private java.lang.Object mensagem_ = "";
    /**
     * <code>string mensagem = 2;</code>
     * @return The mensagem.
     */
    public java.lang.String getMensagem() {
      java.lang.Object ref = mensagem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensagem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mensagem = 2;</code>
     * @return The bytes for mensagem.
     */
    public com.google.protobuf.ByteString
        getMensagemBytes() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensagem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mensagem = 2;</code>
     * @param value The mensagem to set.
     * @return This builder for chaining.
     */
    public Builder setMensagem(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mensagem_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mensagem = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMensagem() {
      
      mensagem_ = getDefaultInstance().getMensagem();
      onChanged();
      return this;
    }
    /**
     * <code>string mensagem = 2;</code>
     * @param value The bytes for mensagem to set.
     * @return This builder for chaining.
     */
    public Builder setMensagemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mensagem_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InserirMatriculaResponse)
  }

  // @@protoc_insertion_point(class_scope:InserirMatriculaResponse)
  private static final InserirMatriculaResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InserirMatriculaResponse();
  }

  public static InserirMatriculaResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InserirMatriculaResponse>
      PARSER = new com.google.protobuf.AbstractParser<InserirMatriculaResponse>() {
    @java.lang.Override
    public InserirMatriculaResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InserirMatriculaResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InserirMatriculaResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public InserirMatriculaResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

