// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

/**
 * Protobuf type {@code InserirMatriculaRequest}
 */
public final class InserirMatriculaRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InserirMatriculaRequest)
    InserirMatriculaRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InserirMatriculaRequest.newBuilder() to construct.
  private InserirMatriculaRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InserirMatriculaRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InserirMatriculaRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_InserirMatriculaRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_InserirMatriculaRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            InserirMatriculaRequest.class, InserirMatriculaRequest.Builder.class);
  }

  public static final int MATRICULA_FIELD_NUMBER = 1;
  private Matricula matricula_;
  /**
   * <code>.Matricula matricula = 1;</code>
   * @return Whether the matricula field is set.
   */
  @java.lang.Override
  public boolean hasMatricula() {
    return matricula_ != null;
  }
  /**
   * <code>.Matricula matricula = 1;</code>
   * @return The matricula.
   */
  @java.lang.Override
  public Matricula getMatricula() {
    return matricula_ == null ? Matricula.getDefaultInstance() : matricula_;
  }
  /**
   * <code>.Matricula matricula = 1;</code>
   */
  @java.lang.Override
  public MatriculaOrBuilder getMatriculaOrBuilder() {
    return getMatricula();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (matricula_ != null) {
      output.writeMessage(1, getMatricula());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (matricula_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMatricula());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof InserirMatriculaRequest)) {
      return super.equals(obj);
    }
    InserirMatriculaRequest other = (InserirMatriculaRequest) obj;

    if (hasMatricula() != other.hasMatricula()) return false;
    if (hasMatricula()) {
      if (!getMatricula()
          .equals(other.getMatricula())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMatricula()) {
      hash = (37 * hash) + MATRICULA_FIELD_NUMBER;
      hash = (53 * hash) + getMatricula().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static InserirMatriculaRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InserirMatriculaRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InserirMatriculaRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InserirMatriculaRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InserirMatriculaRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static InserirMatriculaRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static InserirMatriculaRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InserirMatriculaRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static InserirMatriculaRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static InserirMatriculaRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static InserirMatriculaRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static InserirMatriculaRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(InserirMatriculaRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InserirMatriculaRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InserirMatriculaRequest)
      InserirMatriculaRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_InserirMatriculaRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_InserirMatriculaRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InserirMatriculaRequest.class, InserirMatriculaRequest.Builder.class);
    }

    // Construct using InserirMatriculaRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (matriculaBuilder_ == null) {
        matricula_ = null;
      } else {
        matricula_ = null;
        matriculaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_InserirMatriculaRequest_descriptor;
    }

    @java.lang.Override
    public InserirMatriculaRequest getDefaultInstanceForType() {
      return InserirMatriculaRequest.getDefaultInstance();
    }

    @java.lang.Override
    public InserirMatriculaRequest build() {
      InserirMatriculaRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public InserirMatriculaRequest buildPartial() {
      InserirMatriculaRequest result = new InserirMatriculaRequest(this);
      if (matriculaBuilder_ == null) {
        result.matricula_ = matricula_;
      } else {
        result.matricula_ = matriculaBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof InserirMatriculaRequest) {
        return mergeFrom((InserirMatriculaRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(InserirMatriculaRequest other) {
      if (other == InserirMatriculaRequest.getDefaultInstance()) return this;
      if (other.hasMatricula()) {
        mergeMatricula(other.getMatricula());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMatriculaFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private Matricula matricula_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Matricula, Matricula.Builder, MatriculaOrBuilder> matriculaBuilder_;
    /**
     * <code>.Matricula matricula = 1;</code>
     * @return Whether the matricula field is set.
     */
    public boolean hasMatricula() {
      return matriculaBuilder_ != null || matricula_ != null;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     * @return The matricula.
     */
    public Matricula getMatricula() {
      if (matriculaBuilder_ == null) {
        return matricula_ == null ? Matricula.getDefaultInstance() : matricula_;
      } else {
        return matriculaBuilder_.getMessage();
      }
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Builder setMatricula(Matricula value) {
      if (matriculaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        matricula_ = value;
        onChanged();
      } else {
        matriculaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Builder setMatricula(
        Matricula.Builder builderForValue) {
      if (matriculaBuilder_ == null) {
        matricula_ = builderForValue.build();
        onChanged();
      } else {
        matriculaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Builder mergeMatricula(Matricula value) {
      if (matriculaBuilder_ == null) {
        if (matricula_ != null) {
          matricula_ =
            Matricula.newBuilder(matricula_).mergeFrom(value).buildPartial();
        } else {
          matricula_ = value;
        }
        onChanged();
      } else {
        matriculaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Builder clearMatricula() {
      if (matriculaBuilder_ == null) {
        matricula_ = null;
        onChanged();
      } else {
        matricula_ = null;
        matriculaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public Matricula.Builder getMatriculaBuilder() {
      
      onChanged();
      return getMatriculaFieldBuilder().getBuilder();
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    public MatriculaOrBuilder getMatriculaOrBuilder() {
      if (matriculaBuilder_ != null) {
        return matriculaBuilder_.getMessageOrBuilder();
      } else {
        return matricula_ == null ?
            Matricula.getDefaultInstance() : matricula_;
      }
    }
    /**
     * <code>.Matricula matricula = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Matricula, Matricula.Builder, MatriculaOrBuilder> 
        getMatriculaFieldBuilder() {
      if (matriculaBuilder_ == null) {
        matriculaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Matricula, Matricula.Builder, MatriculaOrBuilder>(
                getMatricula(),
                getParentForChildren(),
                isClean());
        matricula_ = null;
      }
      return matriculaBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InserirMatriculaRequest)
  }

  // @@protoc_insertion_point(class_scope:InserirMatriculaRequest)
  private static final InserirMatriculaRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new InserirMatriculaRequest();
  }

  public static InserirMatriculaRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InserirMatriculaRequest>
      PARSER = new com.google.protobuf.AbstractParser<InserirMatriculaRequest>() {
    @java.lang.Override
    public InserirMatriculaRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InserirMatriculaRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InserirMatriculaRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public InserirMatriculaRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

