// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface InserirMatriculaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InserirMatriculaResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Matricula matricula = 1;</code>
   * @return Whether the matricula field is set.
   */
  boolean hasMatricula();
  /**
   * <code>.Matricula matricula = 1;</code>
   * @return The matricula.
   */
  Matricula getMatricula();
  /**
   * <code>.Matricula matricula = 1;</code>
   */
  MatriculaOrBuilder getMatriculaOrBuilder();

  /**
   * <code>string mensagem = 2;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>string mensagem = 2;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();
}
