// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface InserirMatriculaRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InserirMatriculaRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Matricula matricula = 1;</code>
   * @return Whether the matricula field is set.
   */
  boolean hasMatricula();
  /**
   * <code>.Matricula matricula = 1;</code>
   * @return The matricula.
   */
  Matricula getMatricula();
  /**
   * <code>.Matricula matricula = 1;</code>
   */
  MatriculaOrBuilder getMatriculaOrBuilder();
}
