// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface ListarDisciplinasCursoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListarDisciplinasCursoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 codigoCurso = 1;</code>
   * @return The codigoCurso.
   */
  int getCodigoCurso();
}
