// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface ListarDisciplinasAlunoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListarDisciplinasAlunoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  java.util.List<ListarDisciplinasAlunoResponse.DisciplinaAlunos> 
      getDisciplinasList();
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  ListarDisciplinasAlunoResponse.DisciplinaAlunos getDisciplinas(int index);
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  int getDisciplinasCount();
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  java.util.List<? extends ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder> 
      getDisciplinasOrBuilderList();
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder getDisciplinasOrBuilder(
      int index);

  /**
   * <code>string mensagem = 2;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>string mensagem = 2;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();
}
