// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

/**
 * Protobuf type {@code ListarDisciplinasAlunoRequest}
 */
public final class ListarDisciplinasAlunoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListarDisciplinasAlunoRequest)
    ListarDisciplinasAlunoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListarDisciplinasAlunoRequest.newBuilder() to construct.
  private ListarDisciplinasAlunoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListarDisciplinasAlunoRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListarDisciplinasAlunoRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_ListarDisciplinasAlunoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_ListarDisciplinasAlunoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ListarDisciplinasAlunoRequest.class, ListarDisciplinasAlunoRequest.Builder.class);
  }

  public static final int RA_FIELD_NUMBER = 1;
  private int ra_;
  /**
   * <code>int32 ra = 1;</code>
   * @return The ra.
   */
  @java.lang.Override
  public int getRa() {
    return ra_;
  }

  public static final int ANO_FIELD_NUMBER = 2;
  private int ano_;
  /**
   * <code>int32 ano = 2;</code>
   * @return The ano.
   */
  @java.lang.Override
  public int getAno() {
    return ano_;
  }

  public static final int SEMESTRE_FIELD_NUMBER = 3;
  private int semestre_;
  /**
   * <code>int32 semestre = 3;</code>
   * @return The semestre.
   */
  @java.lang.Override
  public int getSemestre() {
    return semestre_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ra_ != 0) {
      output.writeInt32(1, ra_);
    }
    if (ano_ != 0) {
      output.writeInt32(2, ano_);
    }
    if (semestre_ != 0) {
      output.writeInt32(3, semestre_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ra_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ra_);
    }
    if (ano_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, ano_);
    }
    if (semestre_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, semestre_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ListarDisciplinasAlunoRequest)) {
      return super.equals(obj);
    }
    ListarDisciplinasAlunoRequest other = (ListarDisciplinasAlunoRequest) obj;

    if (getRa()
        != other.getRa()) return false;
    if (getAno()
        != other.getAno()) return false;
    if (getSemestre()
        != other.getSemestre()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RA_FIELD_NUMBER;
    hash = (53 * hash) + getRa();
    hash = (37 * hash) + ANO_FIELD_NUMBER;
    hash = (53 * hash) + getAno();
    hash = (37 * hash) + SEMESTRE_FIELD_NUMBER;
    hash = (53 * hash) + getSemestre();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ListarDisciplinasAlunoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListarDisciplinasAlunoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ListarDisciplinasAlunoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListarDisciplinasAlunoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ListarDisciplinasAlunoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListarDisciplinasAlunoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListarDisciplinasAlunoRequest)
      ListarDisciplinasAlunoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_ListarDisciplinasAlunoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_ListarDisciplinasAlunoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListarDisciplinasAlunoRequest.class, ListarDisciplinasAlunoRequest.Builder.class);
    }

    // Construct using ListarDisciplinasAlunoRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ra_ = 0;

      ano_ = 0;

      semestre_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_ListarDisciplinasAlunoRequest_descriptor;
    }

    @java.lang.Override
    public ListarDisciplinasAlunoRequest getDefaultInstanceForType() {
      return ListarDisciplinasAlunoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ListarDisciplinasAlunoRequest build() {
      ListarDisciplinasAlunoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ListarDisciplinasAlunoRequest buildPartial() {
      ListarDisciplinasAlunoRequest result = new ListarDisciplinasAlunoRequest(this);
      result.ra_ = ra_;
      result.ano_ = ano_;
      result.semestre_ = semestre_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ListarDisciplinasAlunoRequest) {
        return mergeFrom((ListarDisciplinasAlunoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ListarDisciplinasAlunoRequest other) {
      if (other == ListarDisciplinasAlunoRequest.getDefaultInstance()) return this;
      if (other.getRa() != 0) {
        setRa(other.getRa());
      }
      if (other.getAno() != 0) {
        setAno(other.getAno());
      }
      if (other.getSemestre() != 0) {
        setSemestre(other.getSemestre());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ra_ = input.readInt32();

              break;
            } // case 8
            case 16: {
              ano_ = input.readInt32();

              break;
            } // case 16
            case 24: {
              semestre_ = input.readInt32();

              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int ra_ ;
    /**
     * <code>int32 ra = 1;</code>
     * @return The ra.
     */
    @java.lang.Override
    public int getRa() {
      return ra_;
    }
    /**
     * <code>int32 ra = 1;</code>
     * @param value The ra to set.
     * @return This builder for chaining.
     */
    public Builder setRa(int value) {
      
      ra_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ra = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRa() {
      
      ra_ = 0;
      onChanged();
      return this;
    }

    private int ano_ ;
    /**
     * <code>int32 ano = 2;</code>
     * @return The ano.
     */
    @java.lang.Override
    public int getAno() {
      return ano_;
    }
    /**
     * <code>int32 ano = 2;</code>
     * @param value The ano to set.
     * @return This builder for chaining.
     */
    public Builder setAno(int value) {
      
      ano_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ano = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAno() {
      
      ano_ = 0;
      onChanged();
      return this;
    }

    private int semestre_ ;
    /**
     * <code>int32 semestre = 3;</code>
     * @return The semestre.
     */
    @java.lang.Override
    public int getSemestre() {
      return semestre_;
    }
    /**
     * <code>int32 semestre = 3;</code>
     * @param value The semestre to set.
     * @return This builder for chaining.
     */
    public Builder setSemestre(int value) {
      
      semestre_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 semestre = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSemestre() {
      
      semestre_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListarDisciplinasAlunoRequest)
  }

  // @@protoc_insertion_point(class_scope:ListarDisciplinasAlunoRequest)
  private static final ListarDisciplinasAlunoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ListarDisciplinasAlunoRequest();
  }

  public static ListarDisciplinasAlunoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListarDisciplinasAlunoRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListarDisciplinasAlunoRequest>() {
    @java.lang.Override
    public ListarDisciplinasAlunoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListarDisciplinasAlunoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListarDisciplinasAlunoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ListarDisciplinasAlunoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

