// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface ListarDisciplinasCursoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListarDisciplinasCursoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  java.util.List<ListarDisciplinasCursoResponse.DisciplinaCurso> 
      getDisciplinasList();
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  ListarDisciplinasCursoResponse.DisciplinaCurso getDisciplinas(int index);
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  int getDisciplinasCount();
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  java.util.List<? extends ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder> 
      getDisciplinasOrBuilderList();
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder getDisciplinasOrBuilder(
      int index);

  /**
   * <code>string mensagem = 2;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>string mensagem = 2;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();
}
