// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

/**
 * Protobuf type {@code ListarDisciplinasAlunoResponse}
 */
public final class ListarDisciplinasAlunoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListarDisciplinasAlunoResponse)
    ListarDisciplinasAlunoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListarDisciplinasAlunoResponse.newBuilder() to construct.
  private ListarDisciplinasAlunoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListarDisciplinasAlunoResponse() {
    disciplinas_ = java.util.Collections.emptyList();
    mensagem_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListarDisciplinasAlunoResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ListarDisciplinasAlunoResponse.class, ListarDisciplinasAlunoResponse.Builder.class);
  }

  public interface DisciplinaAlunosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ListarDisciplinasAlunoResponse.DisciplinaAlunos)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 ra = 1;</code>
     * @return The ra.
     */
    int getRa();

    /**
     * <code>string codigoDisciplina = 2;</code>
     * @return The codigoDisciplina.
     */
    java.lang.String getCodigoDisciplina();
    /**
     * <code>string codigoDisciplina = 2;</code>
     * @return The bytes for codigoDisciplina.
     */
    com.google.protobuf.ByteString
        getCodigoDisciplinaBytes();

    /**
     * <code>float nota = 3;</code>
     * @return The nota.
     */
    float getNota();

    /**
     * <code>int32 faltas = 4;</code>
     * @return The faltas.
     */
    int getFaltas();
  }
  /**
   * Protobuf type {@code ListarDisciplinasAlunoResponse.DisciplinaAlunos}
   */
  public static final class DisciplinaAlunos extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ListarDisciplinasAlunoResponse.DisciplinaAlunos)
      DisciplinaAlunosOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DisciplinaAlunos.newBuilder() to construct.
    private DisciplinaAlunos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DisciplinaAlunos() {
      codigoDisciplina_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DisciplinaAlunos();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_DisciplinaAlunos_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_DisciplinaAlunos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListarDisciplinasAlunoResponse.DisciplinaAlunos.class, ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder.class);
    }

    public static final int RA_FIELD_NUMBER = 1;
    private int ra_;
    /**
     * <code>int32 ra = 1;</code>
     * @return The ra.
     */
    @java.lang.Override
    public int getRa() {
      return ra_;
    }

    public static final int CODIGODISCIPLINA_FIELD_NUMBER = 2;
    private volatile java.lang.Object codigoDisciplina_;
    /**
     * <code>string codigoDisciplina = 2;</code>
     * @return The codigoDisciplina.
     */
    @java.lang.Override
    public java.lang.String getCodigoDisciplina() {
      java.lang.Object ref = codigoDisciplina_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codigoDisciplina_ = s;
        return s;
      }
    }
    /**
     * <code>string codigoDisciplina = 2;</code>
     * @return The bytes for codigoDisciplina.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodigoDisciplinaBytes() {
      java.lang.Object ref = codigoDisciplina_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codigoDisciplina_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTA_FIELD_NUMBER = 3;
    private float nota_;
    /**
     * <code>float nota = 3;</code>
     * @return The nota.
     */
    @java.lang.Override
    public float getNota() {
      return nota_;
    }

    public static final int FALTAS_FIELD_NUMBER = 4;
    private int faltas_;
    /**
     * <code>int32 faltas = 4;</code>
     * @return The faltas.
     */
    @java.lang.Override
    public int getFaltas() {
      return faltas_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ra_ != 0) {
        output.writeInt32(1, ra_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigoDisciplina_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, codigoDisciplina_);
      }
      if (java.lang.Float.floatToRawIntBits(nota_) != 0) {
        output.writeFloat(3, nota_);
      }
      if (faltas_ != 0) {
        output.writeInt32(4, faltas_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ra_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ra_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigoDisciplina_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, codigoDisciplina_);
      }
      if (java.lang.Float.floatToRawIntBits(nota_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, nota_);
      }
      if (faltas_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, faltas_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ListarDisciplinasAlunoResponse.DisciplinaAlunos)) {
        return super.equals(obj);
      }
      ListarDisciplinasAlunoResponse.DisciplinaAlunos other = (ListarDisciplinasAlunoResponse.DisciplinaAlunos) obj;

      if (getRa()
          != other.getRa()) return false;
      if (!getCodigoDisciplina()
          .equals(other.getCodigoDisciplina())) return false;
      if (java.lang.Float.floatToIntBits(getNota())
          != java.lang.Float.floatToIntBits(
              other.getNota())) return false;
      if (getFaltas()
          != other.getFaltas()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RA_FIELD_NUMBER;
      hash = (53 * hash) + getRa();
      hash = (37 * hash) + CODIGODISCIPLINA_FIELD_NUMBER;
      hash = (53 * hash) + getCodigoDisciplina().hashCode();
      hash = (37 * hash) + NOTA_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getNota());
      hash = (37 * hash) + FALTAS_FIELD_NUMBER;
      hash = (53 * hash) + getFaltas();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ListarDisciplinasAlunoResponse.DisciplinaAlunos prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ListarDisciplinasAlunoResponse.DisciplinaAlunos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ListarDisciplinasAlunoResponse.DisciplinaAlunos)
        ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_DisciplinaAlunos_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_DisciplinaAlunos_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ListarDisciplinasAlunoResponse.DisciplinaAlunos.class, ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder.class);
      }

      // Construct using ListarDisciplinasAlunoResponse.DisciplinaAlunos.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ra_ = 0;

        codigoDisciplina_ = "";

        nota_ = 0F;

        faltas_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_DisciplinaAlunos_descriptor;
      }

      @java.lang.Override
      public ListarDisciplinasAlunoResponse.DisciplinaAlunos getDefaultInstanceForType() {
        return ListarDisciplinasAlunoResponse.DisciplinaAlunos.getDefaultInstance();
      }

      @java.lang.Override
      public ListarDisciplinasAlunoResponse.DisciplinaAlunos build() {
        ListarDisciplinasAlunoResponse.DisciplinaAlunos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ListarDisciplinasAlunoResponse.DisciplinaAlunos buildPartial() {
        ListarDisciplinasAlunoResponse.DisciplinaAlunos result = new ListarDisciplinasAlunoResponse.DisciplinaAlunos(this);
        result.ra_ = ra_;
        result.codigoDisciplina_ = codigoDisciplina_;
        result.nota_ = nota_;
        result.faltas_ = faltas_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ListarDisciplinasAlunoResponse.DisciplinaAlunos) {
          return mergeFrom((ListarDisciplinasAlunoResponse.DisciplinaAlunos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ListarDisciplinasAlunoResponse.DisciplinaAlunos other) {
        if (other == ListarDisciplinasAlunoResponse.DisciplinaAlunos.getDefaultInstance()) return this;
        if (other.getRa() != 0) {
          setRa(other.getRa());
        }
        if (!other.getCodigoDisciplina().isEmpty()) {
          codigoDisciplina_ = other.codigoDisciplina_;
          onChanged();
        }
        if (other.getNota() != 0F) {
          setNota(other.getNota());
        }
        if (other.getFaltas() != 0) {
          setFaltas(other.getFaltas());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ra_ = input.readInt32();

                break;
              } // case 8
              case 18: {
                codigoDisciplina_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 29: {
                nota_ = input.readFloat();

                break;
              } // case 29
              case 32: {
                faltas_ = input.readInt32();

                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int ra_ ;
      /**
       * <code>int32 ra = 1;</code>
       * @return The ra.
       */
      @java.lang.Override
      public int getRa() {
        return ra_;
      }
      /**
       * <code>int32 ra = 1;</code>
       * @param value The ra to set.
       * @return This builder for chaining.
       */
      public Builder setRa(int value) {
        
        ra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ra = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRa() {
        
        ra_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object codigoDisciplina_ = "";
      /**
       * <code>string codigoDisciplina = 2;</code>
       * @return The codigoDisciplina.
       */
      public java.lang.String getCodigoDisciplina() {
        java.lang.Object ref = codigoDisciplina_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          codigoDisciplina_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string codigoDisciplina = 2;</code>
       * @return The bytes for codigoDisciplina.
       */
      public com.google.protobuf.ByteString
          getCodigoDisciplinaBytes() {
        java.lang.Object ref = codigoDisciplina_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          codigoDisciplina_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string codigoDisciplina = 2;</code>
       * @param value The codigoDisciplina to set.
       * @return This builder for chaining.
       */
      public Builder setCodigoDisciplina(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        codigoDisciplina_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string codigoDisciplina = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCodigoDisciplina() {
        
        codigoDisciplina_ = getDefaultInstance().getCodigoDisciplina();
        onChanged();
        return this;
      }
      /**
       * <code>string codigoDisciplina = 2;</code>
       * @param value The bytes for codigoDisciplina to set.
       * @return This builder for chaining.
       */
      public Builder setCodigoDisciplinaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        codigoDisciplina_ = value;
        onChanged();
        return this;
      }

      private float nota_ ;
      /**
       * <code>float nota = 3;</code>
       * @return The nota.
       */
      @java.lang.Override
      public float getNota() {
        return nota_;
      }
      /**
       * <code>float nota = 3;</code>
       * @param value The nota to set.
       * @return This builder for chaining.
       */
      public Builder setNota(float value) {
        
        nota_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float nota = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNota() {
        
        nota_ = 0F;
        onChanged();
        return this;
      }

      private int faltas_ ;
      /**
       * <code>int32 faltas = 4;</code>
       * @return The faltas.
       */
      @java.lang.Override
      public int getFaltas() {
        return faltas_;
      }
      /**
       * <code>int32 faltas = 4;</code>
       * @param value The faltas to set.
       * @return This builder for chaining.
       */
      public Builder setFaltas(int value) {
        
        faltas_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 faltas = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFaltas() {
        
        faltas_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ListarDisciplinasAlunoResponse.DisciplinaAlunos)
    }

    // @@protoc_insertion_point(class_scope:ListarDisciplinasAlunoResponse.DisciplinaAlunos)
    private static final ListarDisciplinasAlunoResponse.DisciplinaAlunos DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ListarDisciplinasAlunoResponse.DisciplinaAlunos();
    }

    public static ListarDisciplinasAlunoResponse.DisciplinaAlunos getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisciplinaAlunos>
        PARSER = new com.google.protobuf.AbstractParser<DisciplinaAlunos>() {
      @java.lang.Override
      public DisciplinaAlunos parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DisciplinaAlunos> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisciplinaAlunos> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ListarDisciplinasAlunoResponse.DisciplinaAlunos getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int DISCIPLINAS_FIELD_NUMBER = 1;
  private java.util.List<ListarDisciplinasAlunoResponse.DisciplinaAlunos> disciplinas_;
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  @java.lang.Override
  public java.util.List<ListarDisciplinasAlunoResponse.DisciplinaAlunos> getDisciplinasList() {
    return disciplinas_;
  }
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder> 
      getDisciplinasOrBuilderList() {
    return disciplinas_;
  }
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  @java.lang.Override
  public int getDisciplinasCount() {
    return disciplinas_.size();
  }
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  @java.lang.Override
  public ListarDisciplinasAlunoResponse.DisciplinaAlunos getDisciplinas(int index) {
    return disciplinas_.get(index);
  }
  /**
   * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
   */
  @java.lang.Override
  public ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder getDisciplinasOrBuilder(
      int index) {
    return disciplinas_.get(index);
  }

  public static final int MENSAGEM_FIELD_NUMBER = 2;
  private volatile java.lang.Object mensagem_;
  /**
   * <code>string mensagem = 2;</code>
   * @return The mensagem.
   */
  @java.lang.Override
  public java.lang.String getMensagem() {
    java.lang.Object ref = mensagem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mensagem_ = s;
      return s;
    }
  }
  /**
   * <code>string mensagem = 2;</code>
   * @return The bytes for mensagem.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMensagemBytes() {
    java.lang.Object ref = mensagem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mensagem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < disciplinas_.size(); i++) {
      output.writeMessage(1, disciplinas_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mensagem_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < disciplinas_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, disciplinas_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mensagem_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ListarDisciplinasAlunoResponse)) {
      return super.equals(obj);
    }
    ListarDisciplinasAlunoResponse other = (ListarDisciplinasAlunoResponse) obj;

    if (!getDisciplinasList()
        .equals(other.getDisciplinasList())) return false;
    if (!getMensagem()
        .equals(other.getMensagem())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDisciplinasCount() > 0) {
      hash = (37 * hash) + DISCIPLINAS_FIELD_NUMBER;
      hash = (53 * hash) + getDisciplinasList().hashCode();
    }
    hash = (37 * hash) + MENSAGEM_FIELD_NUMBER;
    hash = (53 * hash) + getMensagem().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ListarDisciplinasAlunoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListarDisciplinasAlunoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ListarDisciplinasAlunoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListarDisciplinasAlunoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ListarDisciplinasAlunoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListarDisciplinasAlunoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListarDisciplinasAlunoResponse)
      ListarDisciplinasAlunoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListarDisciplinasAlunoResponse.class, ListarDisciplinasAlunoResponse.Builder.class);
    }

    // Construct using ListarDisciplinasAlunoResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (disciplinasBuilder_ == null) {
        disciplinas_ = java.util.Collections.emptyList();
      } else {
        disciplinas_ = null;
        disciplinasBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      mensagem_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_ListarDisciplinasAlunoResponse_descriptor;
    }

    @java.lang.Override
    public ListarDisciplinasAlunoResponse getDefaultInstanceForType() {
      return ListarDisciplinasAlunoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ListarDisciplinasAlunoResponse build() {
      ListarDisciplinasAlunoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ListarDisciplinasAlunoResponse buildPartial() {
      ListarDisciplinasAlunoResponse result = new ListarDisciplinasAlunoResponse(this);
      int from_bitField0_ = bitField0_;
      if (disciplinasBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          disciplinas_ = java.util.Collections.unmodifiableList(disciplinas_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.disciplinas_ = disciplinas_;
      } else {
        result.disciplinas_ = disciplinasBuilder_.build();
      }
      result.mensagem_ = mensagem_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ListarDisciplinasAlunoResponse) {
        return mergeFrom((ListarDisciplinasAlunoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ListarDisciplinasAlunoResponse other) {
      if (other == ListarDisciplinasAlunoResponse.getDefaultInstance()) return this;
      if (disciplinasBuilder_ == null) {
        if (!other.disciplinas_.isEmpty()) {
          if (disciplinas_.isEmpty()) {
            disciplinas_ = other.disciplinas_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDisciplinasIsMutable();
            disciplinas_.addAll(other.disciplinas_);
          }
          onChanged();
        }
      } else {
        if (!other.disciplinas_.isEmpty()) {
          if (disciplinasBuilder_.isEmpty()) {
            disciplinasBuilder_.dispose();
            disciplinasBuilder_ = null;
            disciplinas_ = other.disciplinas_;
            bitField0_ = (bitField0_ & ~0x00000001);
            disciplinasBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDisciplinasFieldBuilder() : null;
          } else {
            disciplinasBuilder_.addAllMessages(other.disciplinas_);
          }
        }
      }
      if (!other.getMensagem().isEmpty()) {
        mensagem_ = other.mensagem_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ListarDisciplinasAlunoResponse.DisciplinaAlunos m =
                  input.readMessage(
                      ListarDisciplinasAlunoResponse.DisciplinaAlunos.parser(),
                      extensionRegistry);
              if (disciplinasBuilder_ == null) {
                ensureDisciplinasIsMutable();
                disciplinas_.add(m);
              } else {
                disciplinasBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              mensagem_ = input.readStringRequireUtf8();

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ListarDisciplinasAlunoResponse.DisciplinaAlunos> disciplinas_ =
      java.util.Collections.emptyList();
    private void ensureDisciplinasIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        disciplinas_ = new java.util.ArrayList<ListarDisciplinasAlunoResponse.DisciplinaAlunos>(disciplinas_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ListarDisciplinasAlunoResponse.DisciplinaAlunos, ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder, ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder> disciplinasBuilder_;

    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public java.util.List<ListarDisciplinasAlunoResponse.DisciplinaAlunos> getDisciplinasList() {
      if (disciplinasBuilder_ == null) {
        return java.util.Collections.unmodifiableList(disciplinas_);
      } else {
        return disciplinasBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public int getDisciplinasCount() {
      if (disciplinasBuilder_ == null) {
        return disciplinas_.size();
      } else {
        return disciplinasBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public ListarDisciplinasAlunoResponse.DisciplinaAlunos getDisciplinas(int index) {
      if (disciplinasBuilder_ == null) {
        return disciplinas_.get(index);
      } else {
        return disciplinasBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder setDisciplinas(
        int index, ListarDisciplinasAlunoResponse.DisciplinaAlunos value) {
      if (disciplinasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisciplinasIsMutable();
        disciplinas_.set(index, value);
        onChanged();
      } else {
        disciplinasBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder setDisciplinas(
        int index, ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder builderForValue) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        disciplinas_.set(index, builderForValue.build());
        onChanged();
      } else {
        disciplinasBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder addDisciplinas(ListarDisciplinasAlunoResponse.DisciplinaAlunos value) {
      if (disciplinasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisciplinasIsMutable();
        disciplinas_.add(value);
        onChanged();
      } else {
        disciplinasBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder addDisciplinas(
        int index, ListarDisciplinasAlunoResponse.DisciplinaAlunos value) {
      if (disciplinasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisciplinasIsMutable();
        disciplinas_.add(index, value);
        onChanged();
      } else {
        disciplinasBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder addDisciplinas(
        ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder builderForValue) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        disciplinas_.add(builderForValue.build());
        onChanged();
      } else {
        disciplinasBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder addDisciplinas(
        int index, ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder builderForValue) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        disciplinas_.add(index, builderForValue.build());
        onChanged();
      } else {
        disciplinasBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder addAllDisciplinas(
        java.lang.Iterable<? extends ListarDisciplinasAlunoResponse.DisciplinaAlunos> values) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, disciplinas_);
        onChanged();
      } else {
        disciplinasBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder clearDisciplinas() {
      if (disciplinasBuilder_ == null) {
        disciplinas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        disciplinasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public Builder removeDisciplinas(int index) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        disciplinas_.remove(index);
        onChanged();
      } else {
        disciplinasBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder getDisciplinasBuilder(
        int index) {
      return getDisciplinasFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder getDisciplinasOrBuilder(
        int index) {
      if (disciplinasBuilder_ == null) {
        return disciplinas_.get(index);  } else {
        return disciplinasBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public java.util.List<? extends ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder> 
         getDisciplinasOrBuilderList() {
      if (disciplinasBuilder_ != null) {
        return disciplinasBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(disciplinas_);
      }
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder addDisciplinasBuilder() {
      return getDisciplinasFieldBuilder().addBuilder(
          ListarDisciplinasAlunoResponse.DisciplinaAlunos.getDefaultInstance());
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder addDisciplinasBuilder(
        int index) {
      return getDisciplinasFieldBuilder().addBuilder(
          index, ListarDisciplinasAlunoResponse.DisciplinaAlunos.getDefaultInstance());
    }
    /**
     * <code>repeated .ListarDisciplinasAlunoResponse.DisciplinaAlunos disciplinas = 1;</code>
     */
    public java.util.List<ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder> 
         getDisciplinasBuilderList() {
      return getDisciplinasFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ListarDisciplinasAlunoResponse.DisciplinaAlunos, ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder, ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder> 
        getDisciplinasFieldBuilder() {
      if (disciplinasBuilder_ == null) {
        disciplinasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ListarDisciplinasAlunoResponse.DisciplinaAlunos, ListarDisciplinasAlunoResponse.DisciplinaAlunos.Builder, ListarDisciplinasAlunoResponse.DisciplinaAlunosOrBuilder>(
                disciplinas_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        disciplinas_ = null;
      }
      return disciplinasBuilder_;
    }

    private java.lang.Object mensagem_ = "";
    /**
     * <code>string mensagem = 2;</code>
     * @return The mensagem.
     */
    public java.lang.String getMensagem() {
      java.lang.Object ref = mensagem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensagem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mensagem = 2;</code>
     * @return The bytes for mensagem.
     */
    public com.google.protobuf.ByteString
        getMensagemBytes() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensagem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mensagem = 2;</code>
     * @param value The mensagem to set.
     * @return This builder for chaining.
     */
    public Builder setMensagem(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mensagem_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mensagem = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMensagem() {
      
      mensagem_ = getDefaultInstance().getMensagem();
      onChanged();
      return this;
    }
    /**
     * <code>string mensagem = 2;</code>
     * @param value The bytes for mensagem to set.
     * @return This builder for chaining.
     */
    public Builder setMensagemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mensagem_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListarDisciplinasAlunoResponse)
  }

  // @@protoc_insertion_point(class_scope:ListarDisciplinasAlunoResponse)
  private static final ListarDisciplinasAlunoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ListarDisciplinasAlunoResponse();
  }

  public static ListarDisciplinasAlunoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListarDisciplinasAlunoResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListarDisciplinasAlunoResponse>() {
    @java.lang.Override
    public ListarDisciplinasAlunoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListarDisciplinasAlunoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListarDisciplinasAlunoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ListarDisciplinasAlunoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

