// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface ListarAlunosRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListarAlunosRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string codigoDisciplina = 1;</code>
   * @return The codigoDisciplina.
   */
  java.lang.String getCodigoDisciplina();
  /**
   * <code>string codigoDisciplina = 1;</code>
   * @return The bytes for codigoDisciplina.
   */
  com.google.protobuf.ByteString
      getCodigoDisciplinaBytes();

  /**
   * <code>int32 ano = 2;</code>
   * @return The ano.
   */
  int getAno();

  /**
   * <code>int32 semestre = 3;</code>
   * @return The semestre.
   */
  int getSemestre();
}
