// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

/**
 * Protobuf type {@code ListarDisciplinasCursoResponse}
 */
public final class ListarDisciplinasCursoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListarDisciplinasCursoResponse)
    ListarDisciplinasCursoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListarDisciplinasCursoResponse.newBuilder() to construct.
  private ListarDisciplinasCursoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListarDisciplinasCursoResponse() {
    disciplinas_ = java.util.Collections.emptyList();
    mensagem_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListarDisciplinasCursoResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ListarDisciplinasCursoResponse.class, ListarDisciplinasCursoResponse.Builder.class);
  }

  public interface DisciplinaCursoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ListarDisciplinasCursoResponse.DisciplinaCurso)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string codigoDisciplina = 1;</code>
     * @return The codigoDisciplina.
     */
    java.lang.String getCodigoDisciplina();
    /**
     * <code>string codigoDisciplina = 1;</code>
     * @return The bytes for codigoDisciplina.
     */
    com.google.protobuf.ByteString
        getCodigoDisciplinaBytes();

    /**
     * <code>string nome = 2;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 2;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string professor = 3;</code>
     * @return The professor.
     */
    java.lang.String getProfessor();
    /**
     * <code>string professor = 3;</code>
     * @return The bytes for professor.
     */
    com.google.protobuf.ByteString
        getProfessorBytes();
  }
  /**
   * Protobuf type {@code ListarDisciplinasCursoResponse.DisciplinaCurso}
   */
  public static final class DisciplinaCurso extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ListarDisciplinasCursoResponse.DisciplinaCurso)
      DisciplinaCursoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DisciplinaCurso.newBuilder() to construct.
    private DisciplinaCurso(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DisciplinaCurso() {
      codigoDisciplina_ = "";
      nome_ = "";
      professor_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DisciplinaCurso();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_DisciplinaCurso_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_DisciplinaCurso_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListarDisciplinasCursoResponse.DisciplinaCurso.class, ListarDisciplinasCursoResponse.DisciplinaCurso.Builder.class);
    }

    public static final int CODIGODISCIPLINA_FIELD_NUMBER = 1;
    private volatile java.lang.Object codigoDisciplina_;
    /**
     * <code>string codigoDisciplina = 1;</code>
     * @return The codigoDisciplina.
     */
    @java.lang.Override
    public java.lang.String getCodigoDisciplina() {
      java.lang.Object ref = codigoDisciplina_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codigoDisciplina_ = s;
        return s;
      }
    }
    /**
     * <code>string codigoDisciplina = 1;</code>
     * @return The bytes for codigoDisciplina.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodigoDisciplinaBytes() {
      java.lang.Object ref = codigoDisciplina_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codigoDisciplina_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 2;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 2;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROFESSOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object professor_;
    /**
     * <code>string professor = 3;</code>
     * @return The professor.
     */
    @java.lang.Override
    public java.lang.String getProfessor() {
      java.lang.Object ref = professor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        professor_ = s;
        return s;
      }
    }
    /**
     * <code>string professor = 3;</code>
     * @return The bytes for professor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProfessorBytes() {
      java.lang.Object ref = professor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        professor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigoDisciplina_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, codigoDisciplina_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nome_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nome_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(professor_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, professor_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(codigoDisciplina_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, codigoDisciplina_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nome_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nome_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(professor_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, professor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ListarDisciplinasCursoResponse.DisciplinaCurso)) {
        return super.equals(obj);
      }
      ListarDisciplinasCursoResponse.DisciplinaCurso other = (ListarDisciplinasCursoResponse.DisciplinaCurso) obj;

      if (!getCodigoDisciplina()
          .equals(other.getCodigoDisciplina())) return false;
      if (!getNome()
          .equals(other.getNome())) return false;
      if (!getProfessor()
          .equals(other.getProfessor())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODIGODISCIPLINA_FIELD_NUMBER;
      hash = (53 * hash) + getCodigoDisciplina().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + PROFESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getProfessor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ListarDisciplinasCursoResponse.DisciplinaCurso parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ListarDisciplinasCursoResponse.DisciplinaCurso prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ListarDisciplinasCursoResponse.DisciplinaCurso}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ListarDisciplinasCursoResponse.DisciplinaCurso)
        ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_DisciplinaCurso_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_DisciplinaCurso_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ListarDisciplinasCursoResponse.DisciplinaCurso.class, ListarDisciplinasCursoResponse.DisciplinaCurso.Builder.class);
      }

      // Construct using ListarDisciplinasCursoResponse.DisciplinaCurso.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        codigoDisciplina_ = "";

        nome_ = "";

        professor_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_DisciplinaCurso_descriptor;
      }

      @java.lang.Override
      public ListarDisciplinasCursoResponse.DisciplinaCurso getDefaultInstanceForType() {
        return ListarDisciplinasCursoResponse.DisciplinaCurso.getDefaultInstance();
      }

      @java.lang.Override
      public ListarDisciplinasCursoResponse.DisciplinaCurso build() {
        ListarDisciplinasCursoResponse.DisciplinaCurso result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ListarDisciplinasCursoResponse.DisciplinaCurso buildPartial() {
        ListarDisciplinasCursoResponse.DisciplinaCurso result = new ListarDisciplinasCursoResponse.DisciplinaCurso(this);
        result.codigoDisciplina_ = codigoDisciplina_;
        result.nome_ = nome_;
        result.professor_ = professor_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ListarDisciplinasCursoResponse.DisciplinaCurso) {
          return mergeFrom((ListarDisciplinasCursoResponse.DisciplinaCurso)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ListarDisciplinasCursoResponse.DisciplinaCurso other) {
        if (other == ListarDisciplinasCursoResponse.DisciplinaCurso.getDefaultInstance()) return this;
        if (!other.getCodigoDisciplina().isEmpty()) {
          codigoDisciplina_ = other.codigoDisciplina_;
          onChanged();
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (!other.getProfessor().isEmpty()) {
          professor_ = other.professor_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                codigoDisciplina_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                nome_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                professor_ = input.readStringRequireUtf8();

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object codigoDisciplina_ = "";
      /**
       * <code>string codigoDisciplina = 1;</code>
       * @return The codigoDisciplina.
       */
      public java.lang.String getCodigoDisciplina() {
        java.lang.Object ref = codigoDisciplina_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          codigoDisciplina_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string codigoDisciplina = 1;</code>
       * @return The bytes for codigoDisciplina.
       */
      public com.google.protobuf.ByteString
          getCodigoDisciplinaBytes() {
        java.lang.Object ref = codigoDisciplina_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          codigoDisciplina_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string codigoDisciplina = 1;</code>
       * @param value The codigoDisciplina to set.
       * @return This builder for chaining.
       */
      public Builder setCodigoDisciplina(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        codigoDisciplina_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string codigoDisciplina = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCodigoDisciplina() {
        
        codigoDisciplina_ = getDefaultInstance().getCodigoDisciplina();
        onChanged();
        return this;
      }
      /**
       * <code>string codigoDisciplina = 1;</code>
       * @param value The bytes for codigoDisciplina to set.
       * @return This builder for chaining.
       */
      public Builder setCodigoDisciplinaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        codigoDisciplina_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 2;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object professor_ = "";
      /**
       * <code>string professor = 3;</code>
       * @return The professor.
       */
      public java.lang.String getProfessor() {
        java.lang.Object ref = professor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          professor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string professor = 3;</code>
       * @return The bytes for professor.
       */
      public com.google.protobuf.ByteString
          getProfessorBytes() {
        java.lang.Object ref = professor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          professor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string professor = 3;</code>
       * @param value The professor to set.
       * @return This builder for chaining.
       */
      public Builder setProfessor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        professor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string professor = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProfessor() {
        
        professor_ = getDefaultInstance().getProfessor();
        onChanged();
        return this;
      }
      /**
       * <code>string professor = 3;</code>
       * @param value The bytes for professor to set.
       * @return This builder for chaining.
       */
      public Builder setProfessorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        professor_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ListarDisciplinasCursoResponse.DisciplinaCurso)
    }

    // @@protoc_insertion_point(class_scope:ListarDisciplinasCursoResponse.DisciplinaCurso)
    private static final ListarDisciplinasCursoResponse.DisciplinaCurso DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ListarDisciplinasCursoResponse.DisciplinaCurso();
    }

    public static ListarDisciplinasCursoResponse.DisciplinaCurso getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DisciplinaCurso>
        PARSER = new com.google.protobuf.AbstractParser<DisciplinaCurso>() {
      @java.lang.Override
      public DisciplinaCurso parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DisciplinaCurso> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DisciplinaCurso> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ListarDisciplinasCursoResponse.DisciplinaCurso getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int DISCIPLINAS_FIELD_NUMBER = 1;
  private java.util.List<ListarDisciplinasCursoResponse.DisciplinaCurso> disciplinas_;
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  @java.lang.Override
  public java.util.List<ListarDisciplinasCursoResponse.DisciplinaCurso> getDisciplinasList() {
    return disciplinas_;
  }
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder> 
      getDisciplinasOrBuilderList() {
    return disciplinas_;
  }
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  @java.lang.Override
  public int getDisciplinasCount() {
    return disciplinas_.size();
  }
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  @java.lang.Override
  public ListarDisciplinasCursoResponse.DisciplinaCurso getDisciplinas(int index) {
    return disciplinas_.get(index);
  }
  /**
   * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
   */
  @java.lang.Override
  public ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder getDisciplinasOrBuilder(
      int index) {
    return disciplinas_.get(index);
  }

  public static final int MENSAGEM_FIELD_NUMBER = 2;
  private volatile java.lang.Object mensagem_;
  /**
   * <code>string mensagem = 2;</code>
   * @return The mensagem.
   */
  @java.lang.Override
  public java.lang.String getMensagem() {
    java.lang.Object ref = mensagem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mensagem_ = s;
      return s;
    }
  }
  /**
   * <code>string mensagem = 2;</code>
   * @return The bytes for mensagem.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMensagemBytes() {
    java.lang.Object ref = mensagem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mensagem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < disciplinas_.size(); i++) {
      output.writeMessage(1, disciplinas_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mensagem_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < disciplinas_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, disciplinas_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensagem_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mensagem_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ListarDisciplinasCursoResponse)) {
      return super.equals(obj);
    }
    ListarDisciplinasCursoResponse other = (ListarDisciplinasCursoResponse) obj;

    if (!getDisciplinasList()
        .equals(other.getDisciplinasList())) return false;
    if (!getMensagem()
        .equals(other.getMensagem())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDisciplinasCount() > 0) {
      hash = (37 * hash) + DISCIPLINAS_FIELD_NUMBER;
      hash = (53 * hash) + getDisciplinasList().hashCode();
    }
    hash = (37 * hash) + MENSAGEM_FIELD_NUMBER;
    hash = (53 * hash) + getMensagem().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ListarDisciplinasCursoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasCursoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasCursoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasCursoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasCursoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ListarDisciplinasCursoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ListarDisciplinasCursoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListarDisciplinasCursoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListarDisciplinasCursoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ListarDisciplinasCursoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ListarDisciplinasCursoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ListarDisciplinasCursoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ListarDisciplinasCursoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListarDisciplinasCursoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListarDisciplinasCursoResponse)
      ListarDisciplinasCursoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ListarDisciplinasCursoResponse.class, ListarDisciplinasCursoResponse.Builder.class);
    }

    // Construct using ListarDisciplinasCursoResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (disciplinasBuilder_ == null) {
        disciplinas_ = java.util.Collections.emptyList();
      } else {
        disciplinas_ = null;
        disciplinasBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      mensagem_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return HelloWorldProto.internal_static_ListarDisciplinasCursoResponse_descriptor;
    }

    @java.lang.Override
    public ListarDisciplinasCursoResponse getDefaultInstanceForType() {
      return ListarDisciplinasCursoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ListarDisciplinasCursoResponse build() {
      ListarDisciplinasCursoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ListarDisciplinasCursoResponse buildPartial() {
      ListarDisciplinasCursoResponse result = new ListarDisciplinasCursoResponse(this);
      int from_bitField0_ = bitField0_;
      if (disciplinasBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          disciplinas_ = java.util.Collections.unmodifiableList(disciplinas_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.disciplinas_ = disciplinas_;
      } else {
        result.disciplinas_ = disciplinasBuilder_.build();
      }
      result.mensagem_ = mensagem_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ListarDisciplinasCursoResponse) {
        return mergeFrom((ListarDisciplinasCursoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ListarDisciplinasCursoResponse other) {
      if (other == ListarDisciplinasCursoResponse.getDefaultInstance()) return this;
      if (disciplinasBuilder_ == null) {
        if (!other.disciplinas_.isEmpty()) {
          if (disciplinas_.isEmpty()) {
            disciplinas_ = other.disciplinas_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDisciplinasIsMutable();
            disciplinas_.addAll(other.disciplinas_);
          }
          onChanged();
        }
      } else {
        if (!other.disciplinas_.isEmpty()) {
          if (disciplinasBuilder_.isEmpty()) {
            disciplinasBuilder_.dispose();
            disciplinasBuilder_ = null;
            disciplinas_ = other.disciplinas_;
            bitField0_ = (bitField0_ & ~0x00000001);
            disciplinasBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDisciplinasFieldBuilder() : null;
          } else {
            disciplinasBuilder_.addAllMessages(other.disciplinas_);
          }
        }
      }
      if (!other.getMensagem().isEmpty()) {
        mensagem_ = other.mensagem_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ListarDisciplinasCursoResponse.DisciplinaCurso m =
                  input.readMessage(
                      ListarDisciplinasCursoResponse.DisciplinaCurso.parser(),
                      extensionRegistry);
              if (disciplinasBuilder_ == null) {
                ensureDisciplinasIsMutable();
                disciplinas_.add(m);
              } else {
                disciplinasBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              mensagem_ = input.readStringRequireUtf8();

              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<ListarDisciplinasCursoResponse.DisciplinaCurso> disciplinas_ =
      java.util.Collections.emptyList();
    private void ensureDisciplinasIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        disciplinas_ = new java.util.ArrayList<ListarDisciplinasCursoResponse.DisciplinaCurso>(disciplinas_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ListarDisciplinasCursoResponse.DisciplinaCurso, ListarDisciplinasCursoResponse.DisciplinaCurso.Builder, ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder> disciplinasBuilder_;

    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public java.util.List<ListarDisciplinasCursoResponse.DisciplinaCurso> getDisciplinasList() {
      if (disciplinasBuilder_ == null) {
        return java.util.Collections.unmodifiableList(disciplinas_);
      } else {
        return disciplinasBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public int getDisciplinasCount() {
      if (disciplinasBuilder_ == null) {
        return disciplinas_.size();
      } else {
        return disciplinasBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public ListarDisciplinasCursoResponse.DisciplinaCurso getDisciplinas(int index) {
      if (disciplinasBuilder_ == null) {
        return disciplinas_.get(index);
      } else {
        return disciplinasBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder setDisciplinas(
        int index, ListarDisciplinasCursoResponse.DisciplinaCurso value) {
      if (disciplinasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisciplinasIsMutable();
        disciplinas_.set(index, value);
        onChanged();
      } else {
        disciplinasBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder setDisciplinas(
        int index, ListarDisciplinasCursoResponse.DisciplinaCurso.Builder builderForValue) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        disciplinas_.set(index, builderForValue.build());
        onChanged();
      } else {
        disciplinasBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder addDisciplinas(ListarDisciplinasCursoResponse.DisciplinaCurso value) {
      if (disciplinasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisciplinasIsMutable();
        disciplinas_.add(value);
        onChanged();
      } else {
        disciplinasBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder addDisciplinas(
        int index, ListarDisciplinasCursoResponse.DisciplinaCurso value) {
      if (disciplinasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDisciplinasIsMutable();
        disciplinas_.add(index, value);
        onChanged();
      } else {
        disciplinasBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder addDisciplinas(
        ListarDisciplinasCursoResponse.DisciplinaCurso.Builder builderForValue) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        disciplinas_.add(builderForValue.build());
        onChanged();
      } else {
        disciplinasBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder addDisciplinas(
        int index, ListarDisciplinasCursoResponse.DisciplinaCurso.Builder builderForValue) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        disciplinas_.add(index, builderForValue.build());
        onChanged();
      } else {
        disciplinasBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder addAllDisciplinas(
        java.lang.Iterable<? extends ListarDisciplinasCursoResponse.DisciplinaCurso> values) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, disciplinas_);
        onChanged();
      } else {
        disciplinasBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder clearDisciplinas() {
      if (disciplinasBuilder_ == null) {
        disciplinas_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        disciplinasBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public Builder removeDisciplinas(int index) {
      if (disciplinasBuilder_ == null) {
        ensureDisciplinasIsMutable();
        disciplinas_.remove(index);
        onChanged();
      } else {
        disciplinasBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public ListarDisciplinasCursoResponse.DisciplinaCurso.Builder getDisciplinasBuilder(
        int index) {
      return getDisciplinasFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder getDisciplinasOrBuilder(
        int index) {
      if (disciplinasBuilder_ == null) {
        return disciplinas_.get(index);  } else {
        return disciplinasBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public java.util.List<? extends ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder> 
         getDisciplinasOrBuilderList() {
      if (disciplinasBuilder_ != null) {
        return disciplinasBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(disciplinas_);
      }
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public ListarDisciplinasCursoResponse.DisciplinaCurso.Builder addDisciplinasBuilder() {
      return getDisciplinasFieldBuilder().addBuilder(
          ListarDisciplinasCursoResponse.DisciplinaCurso.getDefaultInstance());
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public ListarDisciplinasCursoResponse.DisciplinaCurso.Builder addDisciplinasBuilder(
        int index) {
      return getDisciplinasFieldBuilder().addBuilder(
          index, ListarDisciplinasCursoResponse.DisciplinaCurso.getDefaultInstance());
    }
    /**
     * <code>repeated .ListarDisciplinasCursoResponse.DisciplinaCurso disciplinas = 1;</code>
     */
    public java.util.List<ListarDisciplinasCursoResponse.DisciplinaCurso.Builder> 
         getDisciplinasBuilderList() {
      return getDisciplinasFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ListarDisciplinasCursoResponse.DisciplinaCurso, ListarDisciplinasCursoResponse.DisciplinaCurso.Builder, ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder> 
        getDisciplinasFieldBuilder() {
      if (disciplinasBuilder_ == null) {
        disciplinasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ListarDisciplinasCursoResponse.DisciplinaCurso, ListarDisciplinasCursoResponse.DisciplinaCurso.Builder, ListarDisciplinasCursoResponse.DisciplinaCursoOrBuilder>(
                disciplinas_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        disciplinas_ = null;
      }
      return disciplinasBuilder_;
    }

    private java.lang.Object mensagem_ = "";
    /**
     * <code>string mensagem = 2;</code>
     * @return The mensagem.
     */
    public java.lang.String getMensagem() {
      java.lang.Object ref = mensagem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensagem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mensagem = 2;</code>
     * @return The bytes for mensagem.
     */
    public com.google.protobuf.ByteString
        getMensagemBytes() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensagem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mensagem = 2;</code>
     * @param value The mensagem to set.
     * @return This builder for chaining.
     */
    public Builder setMensagem(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mensagem_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string mensagem = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMensagem() {
      
      mensagem_ = getDefaultInstance().getMensagem();
      onChanged();
      return this;
    }
    /**
     * <code>string mensagem = 2;</code>
     * @param value The bytes for mensagem to set.
     * @return This builder for chaining.
     */
    public Builder setMensagemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mensagem_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListarDisciplinasCursoResponse)
  }

  // @@protoc_insertion_point(class_scope:ListarDisciplinasCursoResponse)
  private static final ListarDisciplinasCursoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ListarDisciplinasCursoResponse();
  }

  public static ListarDisciplinasCursoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListarDisciplinasCursoResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListarDisciplinasCursoResponse>() {
    @java.lang.Override
    public ListarDisciplinasCursoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListarDisciplinasCursoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListarDisciplinasCursoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ListarDisciplinasCursoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

