// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface ListarDisciplinasAlunoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListarDisciplinasAlunoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ra = 1;</code>
   * @return The ra.
   */
  int getRa();

  /**
   * <code>int32 ano = 2;</code>
   * @return The ano.
   */
  int getAno();

  /**
   * <code>int32 semestre = 3;</code>
   * @return The semestre.
   */
  int getSemestre();
}
