// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/service.proto

public interface ListarAlunosResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListarAlunosResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ListarAlunosResponse.Aluno alunos = 1;</code>
   */
  java.util.List<ListarAlunosResponse.Aluno> 
      getAlunosList();
  /**
   * <code>repeated .ListarAlunosResponse.Aluno alunos = 1;</code>
   */
  ListarAlunosResponse.Aluno getAlunos(int index);
  /**
   * <code>repeated .ListarAlunosResponse.Aluno alunos = 1;</code>
   */
  int getAlunosCount();
  /**
   * <code>repeated .ListarAlunosResponse.Aluno alunos = 1;</code>
   */
  java.util.List<? extends ListarAlunosResponse.AlunoOrBuilder> 
      getAlunosOrBuilderList();
  /**
   * <code>repeated .ListarAlunosResponse.Aluno alunos = 1;</code>
   */
  ListarAlunosResponse.AlunoOrBuilder getAlunosOrBuilder(
      int index);

  /**
   * <code>string mensagem = 2;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>string mensagem = 2;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();
}
