# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gerenciamentoNotas_pb2 as gerenciamentoNotas__pb2


class GerenciadorDeNotasStub(object):
    """interface de serviço
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InserirMatricula = channel.unary_unary(
                '/GerenciadorDeNotas/InserirMatricula',
                request_serializer=gerenciamentoNotas__pb2.InserirMatriculaRequest.SerializeToString,
                response_deserializer=gerenciamentoNotas__pb2.InserirMatriculaResponse.FromString,
                )
        self.AlterarNota = channel.unary_unary(
                '/GerenciadorDeNotas/AlterarNota',
                request_serializer=gerenciamentoNotas__pb2.AlterarNotaRequest.SerializeToString,
                response_deserializer=gerenciamentoNotas__pb2.AlterarNotaResponse.FromString,
                )
        self.AlterarFaltas = channel.unary_unary(
                '/GerenciadorDeNotas/AlterarFaltas',
                request_serializer=gerenciamentoNotas__pb2.AlterarFaltasRequest.SerializeToString,
                response_deserializer=gerenciamentoNotas__pb2.AlterarFaltasResponse.FromString,
                )
        self.ListarAlunos = channel.unary_unary(
                '/GerenciadorDeNotas/ListarAlunos',
                request_serializer=gerenciamentoNotas__pb2.ListarAlunosRequest.SerializeToString,
                response_deserializer=gerenciamentoNotas__pb2.ListarAlunosResponse.FromString,
                )
        self.ListarDisciplinasAluno = channel.unary_unary(
                '/GerenciadorDeNotas/ListarDisciplinasAluno',
                request_serializer=gerenciamentoNotas__pb2.ListarDisciplinasAlunoRequest.SerializeToString,
                response_deserializer=gerenciamentoNotas__pb2.ListarDisciplinasAlunoResponse.FromString,
                )


class GerenciadorDeNotasServicer(object):
    """interface de serviço
    """

    def InserirMatricula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterarNota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterarFaltas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarAlunos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarDisciplinasAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GerenciadorDeNotasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InserirMatricula': grpc.unary_unary_rpc_method_handler(
                    servicer.InserirMatricula,
                    request_deserializer=gerenciamentoNotas__pb2.InserirMatriculaRequest.FromString,
                    response_serializer=gerenciamentoNotas__pb2.InserirMatriculaResponse.SerializeToString,
            ),
            'AlterarNota': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterarNota,
                    request_deserializer=gerenciamentoNotas__pb2.AlterarNotaRequest.FromString,
                    response_serializer=gerenciamentoNotas__pb2.AlterarNotaResponse.SerializeToString,
            ),
            'AlterarFaltas': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterarFaltas,
                    request_deserializer=gerenciamentoNotas__pb2.AlterarFaltasRequest.FromString,
                    response_serializer=gerenciamentoNotas__pb2.AlterarFaltasResponse.SerializeToString,
            ),
            'ListarAlunos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarAlunos,
                    request_deserializer=gerenciamentoNotas__pb2.ListarAlunosRequest.FromString,
                    response_serializer=gerenciamentoNotas__pb2.ListarAlunosResponse.SerializeToString,
            ),
            'ListarDisciplinasAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarDisciplinasAluno,
                    request_deserializer=gerenciamentoNotas__pb2.ListarDisciplinasAlunoRequest.FromString,
                    response_serializer=gerenciamentoNotas__pb2.ListarDisciplinasAlunoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GerenciadorDeNotas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GerenciadorDeNotas(object):
    """interface de serviço
    """

    @staticmethod
    def InserirMatricula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorDeNotas/InserirMatricula',
            gerenciamentoNotas__pb2.InserirMatriculaRequest.SerializeToString,
            gerenciamentoNotas__pb2.InserirMatriculaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AlterarNota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorDeNotas/AlterarNota',
            gerenciamentoNotas__pb2.AlterarNotaRequest.SerializeToString,
            gerenciamentoNotas__pb2.AlterarNotaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AlterarFaltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorDeNotas/AlterarFaltas',
            gerenciamentoNotas__pb2.AlterarFaltasRequest.SerializeToString,
            gerenciamentoNotas__pb2.AlterarFaltasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarAlunos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorDeNotas/ListarAlunos',
            gerenciamentoNotas__pb2.ListarAlunosRequest.SerializeToString,
            gerenciamentoNotas__pb2.ListarAlunosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListarDisciplinasAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GerenciadorDeNotas/ListarDisciplinasAluno',
            gerenciamentoNotas__pb2.ListarDisciplinasAlunoRequest.SerializeToString,
            gerenciamentoNotas__pb2.ListarDisciplinasAlunoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
